# Site Settings
baseurl: ""
url : "https://jackpraveenraj.github.io"

# Blog Settings
theme_settings :
  title : Jack Ilango
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/profilepic.png
    username : Jack Praveen Raj Ilango
    description : Passionate Engineer, ML Enthusiast. Driven by curiosity. Problem solver who is inspired to find solutions by applying technical knowledge to real life scenarios.
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : HTML5 & CSS
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  jackpraveenraj.work@gmail.com
    linkedin: https://www.linkedin.com/jack-praveen-raj-ilango/
    github: jackpraveeraj
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
