# Site Settings
baseurl: ""
url : "https://jackpraveenraj.github.io"

# Blog Settings
theme_settings :
  title : Jack Ilango
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.jpg
    username : Jack Praveen Raj Ilango
    description : Passionate Engineer, ML Enthusiast. Driven by curiosity. Problem solver who is inspired to find solutions by applying technical knowledge to real life scenarios.
    experience :
      - start : April 2020
        end : Current
        experience : Technical Research Member @ ACM SIGL Student Branch SRM   
        location : SRMIST, Chennai
      - start : March 2020
        end : Current
        experience : Co-Founder and Corporate Strategy and Marketing Team Head @ ACM SIGL Student Branch SRM 
        location : SRMIST, Chennai
      - start : August 2019
        end : Jan 2020
        experience : Technical Team Member @ CSE Association
        location : SRMIST, Chennai
    skills : 
      - skill : Python
      - skill : C/C++
      - skill : Javascript
      - skill : SQL, PL/SQL
      - skill : Dart & Flutter
      - skill : HTML5 & CSS3
      - skill : Deep Learning
      - skill : TensorFlow
      - skill : OpenCV
      - skill : Matlab
  # Icons
  icons :
    email:  jackpraveenraj.work@gmail.com
    linkedin: https://www.linkedin.com/jack-praveen-raj-ilango/
    github: jackpraveeraj
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
